name: Install

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Before Install
        run: |
          sudo apt-get install g++-10
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 90 

      - name: install dependency
        run: sudo apt-get install libboost-dev libboost-container-dev

      - name: build and install library
        run: |
          cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DINSTALL_ONLY=ON
          sudo cmake --build build --target install
          rm -rf build

      - name: configure
        run: cmake -Stest_installed -Bbuild

      - name: build
        run: cmake --build build --config Debug -j4

      - name: run
        run: ./build/test_installed/CkPttn
